# Generated by Django 6.0.4 on 2026-04-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('break_start', models.DateTimeField(blank=True, null=True)),
                ('total_break_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('WORKING', 'Working'), ('ON_BREAK', 'On Break'), ('CLOCKED_OUT', 'Clocked Out'), ('MISSING_CLOCKOUT', 'Missing Clock-out')], default='WORKING', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_out_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=10)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='tracker.dailytimerecord')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(help_text='4-digit PIN for quick login', max_length=4)),
                ('target_hours_per_month', models.DecimalField(decimal_places=2, default=160.0, max_digits=6)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeeprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailytimerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='tracker.employeeprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytimerecord',
            unique_together={('employee', 'date')},
        ),
        migrations.CreateModel(
            name='HRReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('year', models.IntegerField(default=2024)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REMINDER_SENT', 'Reminder Sent'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_reviews', to='tracker.employeeprofile')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
