# Generated by Django 6.0.4 on 2026-04-10 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytimerecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
