# Generated by Django 6.0.4 on 2026-04-10 08:05

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_dailytimerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrreview',
            name='year',
            field=models.IntegerField(default=tracker.models._current_year),
        ),
    ]
